# Generated by Django 4.1.2 on 2023-01-14 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_reviews_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('in-cart', 'in-cart'), ('cancelled', 'cancelled')], default='in-cart', max_length=200),
        ),
        migrations.AlterField(
            model_name='carts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('despathed', 'despatched'), ('in-transit', 'in-transit'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
